[package]
name = "fenix_rooms"
version = "0.1.0"
authors = ["Luís Fiolhais <luisazenhas.fiolhais@openmailbox.org>"]

[dependencies]
pencil = { git = "https://github.com/lfiolhais/pencil", branch = "feature/neg-num"}
log = "0.3"
env_logger = "*"
hyper = "*"
serde_json = "0.8"
serde_derive = "0.8"
serde = "0.8.19"
